### ISSUE TITLE
[ENH] Add Probability Mass Function (`pmf`) and Its Log (`log_pmf`) Methods on Base Distribution Class

### ISSUE THREAD

**Issue by malikrafsan** [sktime/skpro#289]
**Is your feature request related to a problem? Please describe.**

All distribution classes inherit from the `BaseDistribution` class, both discrete and continuous distributions. Currently, the class `BaseDistribition` doesn't have `pmf` and `log_pmf` methods to calculate the value of the probability mass function and its logarithmic, but it has `pdf` and `log_pdf` methods. Probability Mass Function (PMF) and Probability Density Function (PDF) are a bit similar as they are both used to describe probability distributions. But, PMF is for discrete distribution whereas PDF is for continuous distribution.

In this situation, all discrete distribution classes inherit the PDF functionality which they shouldn't have and there are no base methods for PMF

**Describe the solution you'd like**

The solution that I propose is that 
- We create a base class for each discrete and continuous distribution, that inherits from the `BaseDistribution` class. 
- Move the PDF functionality on the base continuous distribution class, so that discrete distributions don't need to implement it
- Add the PMF functionality on the base discrete distributions to accommodate this functionality for all discrete distribution classes

**Describe alternatives you've considered**

Another alternative that we can try is to directly add PMF functionality on the `BaseDistribution` class without adding base discrete and continuous distributions. This solution offers fewer changes but mixes the discrete and continuous functionalities on the base class

**Comment by fkiraly** [comment]
I would go with the alternative, i.e., one class, because it also allows to deal with *mixed* distributions, i.e., distributions that have a continuous and a discrete part, both (e.g., clipped normal).

There is a design discussion here: https://github.com/sktime/skpro/issues/229 - which @shreeesham07 has commented on, FYI @shreesham07 re this issue.

The solution would see `pdf` of discrete distributions return zero, and `pmf` of continuous distributions return zero.
